### ISSUE TITLE
Webp image upload issue

### ISSUE THREAD

**Issue by SRIKANTHAR** [ruby/open-uri#17]
webp images upload not supported it's giving this error message when trying to upload webp images has below

avatar_2_3_webp = open(webp_image_url)

at method "open" we are getting this error

ImageSpec::Error (#Paperclip::Tempfile:/tmp/18c5a2261d1d178068acb724a8a967b720221108-1242657-rpwwg520221108-1242657-n7zd3k.webp is not a supported image format. Sorry bub :():

we are using Rails 4.2 and ruby 2.3.0

please help on this to how to fix this issue

**Comment by hsbt** [comment]
It's not `open-uri` issue. You should ask https://stackoverflow.com/ or https://github.com/thoughtbot/paperclip
